# https://techoverflow.net/2021/11/25/how-to-setup-standalone-mosquitto-mqtt-broker-using-docker-compose/

version: '3.7'

services:
  main:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    tty: true
    container_name: 'mqtt_broker'
